# Generated by Django 4.0 on 2022-12-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_schedulecal', '0003_event_delete_schedulecalendar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
