# Generated by Django 4.0 on 2022-12-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pengguna',
        ),
    ]
