# Generated by Django 4.0 on 2022-12-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus_session', '0002_remove_chek_date_chek_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chek',
        ),
    ]
